### ISSUE TITLE
已 vpn 科学上网

### ISSUE THREAD

**Issue by jurimengs** [HVision-NKU/StoryDiffusion#139]
python gradio_app_sdxl_specific_id_low_vram.py

Traceback (most recent call last):
  File "D:\jurim\codes\github\story-diffusion\gradio_app_sdxl_specific_id_low_vram.py", line 45, in <module>
    photomaker_path =  hf_hub_download(repo_id="TencentARC/PhotoMaker", filename="photomaker-v1.bin", repo_type="model")
  File "D:\jurim\ProgramData\anaconda3\envs\storydiffusion\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\jurim\ProgramData\anaconda3\envs\storydiffusion\lib\site-packages\huggingface_hub\file_download.py", line 1371, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

**Comment by KhunLounZai** [comment]
代码里加这个  os.environ["HF_ENDPOINT"] = "https://hf-mirror.com" 就OK了

**Comment by JimWang151** [comment]
> 代码里加这个 os.environ["HF_ENDPOINT"] = "https://hf-mirror.com" 就OK了
兄弟，指点一下，是把这个代码加到下面这个文件里面吗？

_**“*****lib\site-packages\huggingface_hub\file_download.py”**_ ？

**Comment by JimWang151** [comment]
> gradio_app_sdxl_specific_id_low_vram.py

谢谢。
