### ISSUE TITLE
can't run the gradio_app_sdxl_specific_id_low_vram.py

### ISSUE THREAD

**Issue by youkerWANG** [HVision-NKU/StoryDiffusion#143]
i run this in the docker env ,this is the issues feed back 
Traceback (most recent call last):
  File "/home/StoryDiffusion/gradio_app_sdxl_specific_id_low_vram.py", line 2, in <module>
    import gradio as gr
  File "/root/miniconda3/envs/story/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "/root/miniconda3/envs/story/lib/python3.10/site-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "/root/miniconda3/envs/story/lib/python3.10/site-packages/gradio/_simple_templates/simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "/root/miniconda3/envs/story/lib/python3.10/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/root/miniconda3/envs/story/lib/python3.10/site-packages/gradio/components/annotated_image.py", line 7, in <module>
    import gradio_client.utils as client_utils
  File "/root/miniconda3/envs/story/lib/python3.10/site-packages/gradio_client/__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "/root/miniconda3/envs/story/lib/python3.10/site-packages/gradio_client/client.py", line 29, in <module>
    from huggingface_hub import CommitOperationAdd, SpaceHardware, SpaceStage
ImportError: cannot import name 'CommitOperationAdd' from 'huggingface_hub' (/root/miniconda3/envs/story/lib/python3.10/site-packages/huggingface_hub/__init__.py)

**Comment by ArianaStar** [comment]
Simply run `pip uninstall huggingface-hub`
Then run `pip install huggingface-hub`

In short huggingface-hub changes frequently, yet can be updated without breaking the process.
