### ISSUE TITLE
Line 430 Error

### ISSUE THREAD

**Issue by dyter07** [HVision-NKU/StoryDiffusion#15]
(storydiffusion) Ubuntu@0021-kci-prxmx10011:~/StoryDiffusion$ ls
app.py			fonts				README.md
Comic_Generation.ipynb	gradio_app_sdxl_specific_id.py	requirements.txt
examples		images				utils
(storydiffusion) Ubuntu@0021-kci-prxmx10011:~/StoryDiffusion$ python gradio_app_sdxl_specific_id.py 
Loading pipeline components...:  14%|█▊           | 1/7 [00:00<00:00, 61.42it/s]
Traceback (most recent call last):
  File "/home/Ubuntu/StoryDiffusion/gradio_app_sdxl_specific_id.py", line 430, in <module>
    pipe = StableDiffusionXLPipeline.from_pretrained(sd_model_path, torch_dtype=torch.float16, use_safetensors=True if use_va else False)
  File "/home/Ubuntu/miniconda3/envs/storydiffusion/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/Ubuntu/miniconda3/envs/storydiffusion/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1271, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/home/Ubuntu/miniconda3/envs/storydiffusion/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 525, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/home/Ubuntu/miniconda3/envs/storydiffusion/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3206, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /home/Ubuntu/.cache/huggingface/hub/models--SG161222--RealVisXL_V4.0/snapshots/49740684ab2d8f4f5dcf6c644df2b33388a8ba85/text_encoder_2.

I got this error, any clue?

**Comment by allthatido** [comment]
if you run app.py it downloads all the file in huggingface hub cache

**Comment by Z-YuPeng** [comment]
@dyter07  Hi, This error has been fixed by the latest code, please git pull  and run
python gradio_app_sdxl_specific_id.py
