### ISSUE TITLE
Running gradio under Windows

### ISSUE THREAD

**Issue by SoftologyPro** [HVision-NKU/StoryDiffusion#3]
`python gradio_app_sdxl_specific_id.py`
gives
`ValueError: The provided pretrained_model_name_or_path "/mnt/bn/yupengdata2/projects/PhotoMaker/RealVisXL_V4.0" is neither a valid local path nor a valid repo id. Please check the parameter.`
which makes sense because that directory does not exist.
Changing the code to
```
models_dict = {
   "Juggernaut":"RunDiffusion/Juggernaut-XL-v8",
   "RealVision":"SG161222/RealVisXL_V4.0" ,
   "SDXL":"stabilityai/stable-diffusion-xl-base-1.0" ,
   "Unstable":"stablediffusionapi/sdxl-unstable-diffusers-y"
}
```
does get the models downloading when the script first starts, but then gives the error
`OSError: Error no file named diffusion_pytorch_model.bin found in directory D:\code\delphi\Chaos\Examples\MachineLearning\.cache\hub\models--SG161222--RealVisXL_V4.0\snapshots\49740684ab2d8f4f5dcf6c644df2b33388a8ba85\vae.`
How can we get the required models tro download correctly?  Thanks.

**Comment by SoftologyPro** [comment]
To get around the model issue I created a model subdirectory then git cloned the models under it
```
git clone https://huggingface.co/RunDiffusion/Juggernaut-XL-v8
git clone https://huggingface.co/SG161222/RealVisXL_V4.0
git clone https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0
git clone https://huggingface.co/stablediffusionapi/sdxl-unstable-diffusers-y
```
and changed the script code to
```
models_dict = {
   "Juggernaut":"./models/Juggernaut-XL-v8" if not use_va else "RunDiffusion/Juggernaut-XL-v8",
   "RealVision":"./models/RealVisXL_V4.0" if not use_va else "SG161222/RealVisXL_V4.0" ,
   "SDXL":"./models/stable-diffusion-xl-base-1.0" if not use_va else "stabilityai/stable-diffusion-xl-base-1.0" ,
   "Unstable":"./models/sdxl-unstable-diffusers-y" if not use_va else "stablediffusionapi/sdxl-unstable-diffusers-y"
}
```
Where should I download/clone this from?
`photomaker_path = "/mnt/bn/dq-storage-ckpt/zyp/magicstory_dev/photomaker-v1.bin" if use_va else "/mnt/bn/yupengdata2/projects/PhotoMaker/photomaker-v1.bin"`
Also, can you change the image format from webp to png?  Makes them easier to save and use with other editors.

**Comment by Z-YuPeng** [comment]
Hi,  I previously tested using local weights and forgot to remove them. I have now modified the code, so it no longer requires loading any local weights. Please run git pull to update, and thank you again for your attention. 
Also, Image format, do you mean the ref image in example DIR? I have changed the image format from JPEG to png

**Comment by Z-YuPeng** [comment]
> git clone https://huggingface.co/RunDiffusion/Juggernaut-XL-v8
> git clone https://huggingface.co/SG161222/RealVisXL_V4.0

Also, `git lfs clone` these pre-trained models is a good idea in the area of downloading these pre-trained models costs too much time, thanks for your advice!

**Comment by Spr-Peach** [comment]
> Hi, I previously tested using local weights and forgot to remove them. I have now modified the code, so it no longer requires loading any local weights. Please run git pull to update, and thank you again for your attention. Also, Image format, do you mean the ref image in example DIR? I have changed the image format from JPEG to png

still reported no fiel named diffusion_pytorch_model.bin after git pull, actually nothing was be updated and shown already up to date...
please help...

**Comment by Spr-Peach** [comment]
I see, just clone those 4 models and copy into corresponding folders under .cache path

**Comment by Spr-Peach** [comment]
and It throws a new error：
<details><summary>Details</summary>
<p>

Traceback (most recent call last):
  File "C:\Users\namiachy\StoryDiffusion\venv\lib\site-packages\gradio\queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\namiachy\StoryDiffusion\venv\lib\site-packages\gradio\route_utils.py", line 258, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\namiachy\StoryDiffusion\venv\lib\site-packages\gradio\blocks.py", line 1710, in process_api
    result = await self.call_function(
  File "C:\Users\namiachy\StoryDiffusion\venv\lib\site-packages\gradio\blocks.py", line 1262, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\namiachy\StoryDiffusion\venv\lib\site-packages\gradio\utils.py", line 517, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\namiachy\StoryDiffusion\venv\lib\site-packages\gradio\utils.py", line 510, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\namiachy\StoryDiffusion\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\namiachy\StoryDiffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\Users\namiachy\StoryDiffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\Users\namiachy\StoryDiffusion\venv\lib\site-packages\gradio\utils.py", line 493, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\namiachy\StoryDiffusion\venv\lib\site-packages\gradio\utils.py", line 676, in gen_wrapper
    response = next(iterator)
  File "C:\Users\namiachy\StoryDiffusion\gradio_app_sdxl_specific_id.py", line 591, in process_generation
    total_results = get_comic(id_images + real_images, _comic_type,captions= captions,font=ImageFont.truetype("./fonts/Inkfree.ttf", int(45))) + total_results
  File "C:\Users\namiachy\StoryDiffusion\utils\utils.py", line 97, in get_comic
    return get_comic_classical(images,captions,font,pad_image)
  File "C:\Users\namiachy\StoryDiffusion\utils\utils.py", line 113, in get_comic_classical
    pad_image = pad_image.resize(images[0].size, Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

</p>
</details> 

please help ...

**Comment by SoftologyPro** [comment]
> and It throws a new error：
get_comic_classical pad_image = pad_image.resize(images[0].size, Image.ANTIALIAS) AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
> 
> please help ...

To fix that you need to roll back pillow, ie

pip uninstall -y pillow
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts pillow==9.5.0

**Comment by SoftologyPro** [comment]
> Hi, I previously tested using local weights and forgot to remove them. I have now modified the code, so it no longer requires loading any local weights. Please run git pull to update, and thank you again for your attention. Also, Image format, do you mean the ref image in example DIR? I have changed the image format from JPEG to png

I mean the generated images in the gradio UI once the comic panbel is created.  It seems to be a webp format.  png would be easier.

**Comment by SoftologyPro** [comment]
> I see, just clone those 4 models and copy into corresponding folders under .cache path

It would be easier if your script auto-downloaded the required models into the user .cache directory without them having to go and clone repositories and copy them around.

**Comment by SoftologyPro** [comment]
Also one more tip.  The IP should be 127.0.0.1 to work when clicked on Windows and share should be False by default for security.
`demo.launch(server_name="127.0.0.1", share = False if use_va else False)`

**Comment by brentjohnston** [comment]
I'm very confused by this project, all the advertising of video generation and I finally got it working and got the models.

I assumed the pipeline.py was doing some sort of magic to the checkpoints, but all it did was generate ipadapter / id_encoder images, what's the point in advertising all the video stuff if we can't test the video out and the online gradio demo doesn't work either?  I don't understand these "legal" issue things mentioned, I just read that comment from dev.

I've made better videos with a more advanced comfyui workflow and modified Comfy-SVDTools timestep and attn window code modifications, latent blends, and SVD model  merges, (a couple of the blocks merge and make it better) and loras on the SVD model which produces error but also some of the blocks seem to merge somehow in comfyui, I'll be releasing workflow and code soon.  I've gotten a consistent 96 frames with a lot of motion and facial expressions. I don't get this repo.

**Comment by SoftologyPro** [comment]
See the To Do section.  Video is coming soon.  I do agree all repos should not release anything until they are done and ready, but they do encounter legal or other issues sometimes outside their control which stop them releasing.  At this stage this gradio generates only the comic panel images.

**Comment by brentjohnston** [comment]
Yeah I saw it before I downloaded, but I assumed even a little code would at least be there in the pipeline.py, there is nothing there for video at all. 

I forgot to mention for this workflow for SVD I also do batch whole_image input of 48 random generated images into into latent ksampler in the comfyui workflow, which I will release. 

Am I supposed to be worried about getting sued also? This is what section 230 is for if you are in the US, unless you are worried about model being trained on copyright material but as openai has said "training AI models using publicly available internet materials is fair use, as supported by long-standing and widely accepted precedents". I dunno something just seems off. Sorry if I'm coming off as brusk btw.

**Comment by christiandarkin** [comment]
> I forgot to mention for this upcoming workflow I made for SVD, I also do batch whole_image input of 48-96 random generated images, or you can use real images into into latent input on ksampler in the comfyui workflow, which I will release.
> 
> 
I'd be very interested in your svg workflow for a project I'm working on (trying to reconstruct missing Dr who episodes from the 60s using old off screen photos and audio tapes)
I'd love to see how your workflpw does..

**Comment by j2l** [comment]
@christiandarkin not sure something will be published, @brentjohnston doesn't have any repo.

**Comment by brentjohnston** [comment]
> @christiandarkin not sure something will be published, @brentjohnston doesn't have any repo. Copyright law is the concern of model makers, not people sharing workflows.

It will be published and i'll post link here, probably need a week or two to finalize. This is not my main account for repo.. Dont want to get sued (jk, joke lol) not a concern as this is fair use and I believe will be a net positive, the bad stuff people will just become desensitized to. Worst case, I'm sure ill see a naked ai video of me somewhere wearing a thong or worse and care less, and so will everyone else.

Ps. I also have a star trek tng computer I will share at some point, with the alltalk_tts finetuned model. Its cloned computer voice that sounds exactly like the next generation version of the ships computer. 

This is through text-generation-web-ui. I also have the voice clone of my voice for a company project, with llm trained on company data, sounding better than elevenlabs v2 now. https://old.reddit.com/r/Oobabooga/comments/1bj7tx4/guide_the_easiest_way_to_modify_oobabooga_colors/

**Comment by brentjohnston** [comment]
> > I forgot to mention for this upcoming workflow I made for SVD, I also do batch whole_image input of 48-96 random generated images, or you can use real images into into latent input on ksampler in the comfyui workflow, which I will release.
> 
> I'd be very interested in your svg workflow for a project I'm working on (trying to reconstruct missing Dr who episodes from the 60s using old off screen photos and audio tapes) I'd love to see how your workflpw does..

Yup ill post it here in next week or two. It will require you to download a custom merged svd model, older comfyui commit for the whole_batch image latent inputs, its modified was batch node thanks to a reddit user,, and modified attention_patch.py from the Comfy-SVDTools repo, comfy math. So it's kind of a bit of setup. I'll give exact instructions. It's very similar videos to this repo but a bit longer in length

**Comment by SoftologyPro** [comment]
Anyway, back on topic to StoryDiffusion.
For now the comic image creation works fine with manual model downloads.  If the script could be changed to auto-download the needed models that would make it much easier for users.

**Comment by Z-YuPeng** [comment]
HI, @SoftologyPro  Thank you again for your attention to our work.
could you try 
pip install safetensors==0.4.0

**Comment by SoftologyPro** [comment]
I had safetensors 0.4.3, rolling back to 0.4.0 still gives this error.  It does start to download the model files, but then fails for some reason (it is way too quick) then it errors out with the cannot find file.  I deleted the cache directory and tried again, same error.

OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory D:\code\delphi\Chaos\Examples\MachineLearning\.cache\hub\models--SG161222--RealVisXL_V4.0\snapshots\49740684ab2d8f4f5dcf6c644df2b33388a8ba85\text_encoder_2.

**Comment by Z-YuPeng** [comment]
@SoftologyPro  Sorry to bother you again. I modify the code to load_safe_tensor = True.
I do not have a Windows machine that has a GPU, if still does not work, I would borrow a computer, to test it.

**Comment by SoftologyPro** [comment]
> @SoftologyPro Sorry to bother you again. I modify the code to load_safe_tensor = True. Could you git pull and try again? I do not have a Windows machine that has a GPU, if still does not work, I would borrow a computer, to test it.

OK, that works :) Thanks.  No need to manually download the models any more.
I am happy to test under Windows.

**Comment by tiwentichat** [comment]
> Hi, I previously tested using local weights and forgot to remove them. I have now modified the code, so it no longer requires loading any local weights. Please run git pull to update, and thank you again for your attention. Also, Image format, do you mean the ref image in example DIR? I have changed the image format from JPEG to png

Hi dude, would like to tell me the path of folder where  the pre-trained models finally put in.

Cache of C disk is not enough for these big files T T


<img width="485" alt="12" src="https://github.com/HVision-NKU/StoryDiffusion/assets/125454744/5d46edaa-214c-4906-8802-3ecb04bb9f84">

大佬救命啊，这几个大的模型最后放在哪个文件夹啊，我提前下好放进去，这样执行 python gradio_app_sdxl_specific_id.py
时就不用再重新下载了，这样可以吗？看起来最上面的那位兄弟 这些代码好像也是像这样搞？

"./models/Juggernaut-XL-v8"所以最后会是在根目录/models里面吗

救救救救救命啊

```
models_dict = {
   "Juggernaut":"./models/Juggernaut-XL-v8" if not use_va else "RunDiffusion/Juggernaut-XL-v8",
   "RealVision":"./models/RealVisXL_V4.0" if not use_va else "SG161222/RealVisXL_V4.0" ,
   "SDXL":"./models/stable-diffusion-xl-base-1.0" if not use_va else "stabilityai/stable-diffusion-xl-base-1.0" ,
   "Unstable":"./models/sdxl-unstable-diffusers-y" if not use_va else "stablediffusionapi/sdxl-unstable-diffusers-y"
}
```

**Comment by j2l** [comment]
> Wall of text, but yes I will publish it and i'll post link here and banodoco discord, probably need a week or two to finalize. 

Happy to read that. Sorry if I mistaken @brentjohnston

**Comment by zhoudaquan** [comment]
Hi guys,

Thanks for your interest! Running the code on windows is important. If you have further questions, please consider to join the discord for better communication: https://discord.gg/2HFUHT9p

Best regards,
DQ

**Comment by espedair-systems** [comment]
> > I see, just clone those 4 models and copy into corresponding folders under .cache path
> 
> It would be easier if your script auto-downloaded the required models into the user .cache directory without them having to go and clone repositories and copy them around. That is how most other AI systems handle the models.
> 
> With the latest code I now get `OSError: Error no file named diffusion_pytorch_model.bin found in directory <cache_path>\.cache\hub\models--SG161222--RealVisXL_V4.0\snapshots\49740684ab2d8f4f5dcf6c644df2b33388a8ba85\vae.`
> 
> It does auto-download the photomaker model, so that now works.

I added 

**_snapshot_download(repo_id="SG161222/RealVisXL_V4.0")_**

Below the line 

photomaker_path =  hf_hub_download(repo_id="TencentARC/PhotoMaker", filename="photomaker-v1.bin", repo_type="model")

But it would be good to pick up the models from the Stable Diffusion downloads I have for ConfyUI as a safetensor file.

**Comment by Spr-Peach** [comment]
> > Hi, I previously tested using local weights and forgot to remove them. I have now modified the code, so it no longer requires loading any local weights. Please run git pull to update, and thank you again for your attention. Also, Image format, do you mean the ref image in example DIR? I have changed the image format from JPEG to png
> 
> Hi dude, would like to tell me the path of folder where the pre-trained models finally put in.
> 
> Cache of C disk is not enough for these big files T T
> 
> <img alt="12" width="485" src="https://private-user-images.githubusercontent.com/125454744/328015224-5d46edaa-214c-4906-8802-3ecb04bb9f84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTQ2MTEsIm5iZiI6MTcxNTAxNDMxMSwicGF0aCI6Ii8xMjU0NTQ3NDQvMzI4MDE1MjI0LTVkNDZlZGFhLTIxNGMtNDkwNi04ODAyLTNlY2IwNGJiOWY4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQxNjUxNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGI0OGEwNzY2MjJkYzU5MzdjNmZlOTcxYTljMDAxYjFlNDIyM2Q4N2I4ZDUzOWU5OTFiNzQ5MDZkYjNiNWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jL9RAZ0kqe0pgJJ81mIMwZAs0Jru11SQGSEw23PT-Ks">
> 大佬救命啊，这几个大的模型最后放在哪个文件夹啊，我提前下好放进去，这样执行 python gradio_app_sdxl_specific_id.py 时就不用再重新下载了，这样可以吗？看起来最上面的那位兄弟 这些代码好像也是像这样搞？
> 
> "./models/Juggernaut-XL-v8"所以最后会是在根目录/models里面吗
> 
> 救救救救救命啊
> 
> ```
> models_dict = {
>    "Juggernaut":"./models/Juggernaut-XL-v8" if not use_va else "RunDiffusion/Juggernaut-XL-v8",
>    "RealVision":"./models/RealVisXL_V4.0" if not use_va else "SG161222/RealVisXL_V4.0" ,
>    "SDXL":"./models/stable-diffusion-xl-base-1.0" if not use_va else "stabilityai/stable-diffusion-xl-base-1.0" ,
>    "Unstable":"./models/sdxl-unstable-diffusers-y" if not use_va else "stablediffusionapi/sdxl-unstable-diffusers-y"
> }
> ```

As what Dr.[SoftologyPro](https://github.com/SoftologyPro) said you can just delete those 3 folders under the path ".cache\huggingface\hub\" : "models--stablediffusionapi--sdxl-unstable-diffusers-y","models--RunDiffusion--Juggernaut-XL-v8" and "models--SG161222--RealVisXL_V4.0", then run "git pull" under venv. Run "python gradio_app_sdxl_specific_id.py" and select a model in the webui, any missing model will auto be downloaded. Haha~

**Comment by dubeno** [comment]
cp C disc's  .cache directory to xxxx path  then set env variables HF_HOME=xxxx , you don't need to set your abs path
